import type { Metadata } from "next";
import "./globals.css";
import { vazirMatn } from "@/utils/fonts";
import Layout from "@/layout/Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`bg-slate-200 ${vazirMatn.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
